using System;
using System.Collections.Generic;

namespace MilanCorp.Domain
{
    public partial class Mlveiculos
    {
        public Mlveiculos()
        {
            MldocumentosVeic = new HashSet<MldocumentosVeic>();
            MlprocessoTransf = new HashSet<MlprocessoTransf>();
            MlremocoesVeic = new HashSet<MlremocoesVeic>();
        }

        public int CodBem { get; set; }
        public short CodTipoBem { get; set; }
        public short? Idantigo { get; set; }
        public string CaminhoFotoAnt { get; set; }
        public string Placa { get; set; }
        public bool VeicSemPlaca { get; set; }
        public string Chassi { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string AnoMod { get; set; }
        public string Cor { get; set; }
        public int? Quilometragem { get; set; }
        public bool Importado { get; set; }
        public string Filiais { get; set; }
        public string Origem { get; set; }
        public string OrigemEst { get; set; }
        public string Etiqueta { get; set; }
        public string Salvado { get; set; }
        public string Sinistro { get; set; }
        public string Nfremocao { get; set; }
        public DateTime? DataMolicar { get; set; }
        public decimal? ValorMolicar { get; set; }
        public double? IndiceDesv { get; set; }
        public decimal? ValorAvaria { get; set; }
        public decimal? ValorLiquido { get; set; }
        public string Transportador { get; set; }
        public string Motorista { get; set; }
        public string Vistoriador { get; set; }
        public string Comb { get; set; }
        public byte Classificacao { get; set; }
        public bool? Sucata { get; set; }
        public string NumMotor { get; set; }
        public bool ChassiRemarcado { get; set; }
        public bool Recompra { get; set; }
        public byte? CabineMonobloco { get; set; }
        public byte? LateralPortaDir { get; set; }
        public byte? LateralPortaEsq { get; set; }
        public byte? Pintura { get; set; }
        public byte? RevestInt { get; set; }
        public byte? Teto { get; set; }
        public byte? TetoSolar { get; set; }
        public byte? CapoDianteiro { get; set; }
        public byte? CapoTraseiro { get; set; }
        public byte? ParaChoqueDiant { get; set; }
        public byte? ParaChoqueTras { get; set; }
        public byte? Estribos { get; set; }
        public byte? Grades { get; set; }
        public byte? ParaLamasEsq { get; set; }
        public byte? Assoalhos { get; set; }
        public byte? AerofolioSuperior { get; set; }
        public byte? AerofolioInferior { get; set; }
        public byte? ParaLamasDir { get; set; }
        public byte? PainelDiant { get; set; }
        public byte? SuportePlacas { get; set; }
        public byte? Estofamento { get; set; }
        public byte? TapeteCarpete { get; set; }
        public byte? BancosTecido { get; set; }
        public byte? BancosCouro { get; set; }
        public byte? CaixaInferiorPorta { get; set; }
        public byte? Bagageiro { get; set; }
        public byte? FechadChaves { get; set; }
        public byte? Motor { get; set; }
        public byte? BombaInjetora { get; set; }
        public byte? Carburador { get; set; }
        public byte? MotorArranque { get; set; }
        public byte? Bobina { get; set; }
        public byte? Bateria { get; set; }
        public byte? Distribuidor { get; set; }
        public byte? Alternador { get; set; }
        public byte? Freios { get; set; }
        public byte? Embreagem { get; set; }
        public byte? Cambio { get; set; }
        public byte? SuspencaoDiant { get; set; }
        public byte? SuspencaoTras { get; set; }
        public byte? Carter { get; set; }
        public byte? Rodas { get; set; }
        public byte? RodasEspeciais { get; set; }
        public byte? DirecaoVolante { get; set; }
        public byte? Diferencial { get; set; }
        public byte? FaroisLd { get; set; }
        public byte? FaroisLe { get; set; }
        public byte? FaroisAuxiliaresLe { get; set; }
        public byte? FaroisAuxiliaresLd { get; set; }
        public byte? LantLdt { get; set; }
        public byte? LantLdd { get; set; }
        public byte? LantLed { get; set; }
        public byte? LantLet { get; set; }
        public byte? LimpadorParaBrisa { get; set; }
        public byte? ArCondicionado { get; set; }
        public byte? DirecaoHidraulica { get; set; }
        public byte? InjecaoEletronica { get; set; }
        public byte? InstrumentoPainel { get; set; }
        public byte? Buzina { get; set; }
        public byte? Tampao { get; set; }
        public byte? ManualProprietario { get; set; }
        public byte? Acendedor { get; set; }
        public byte? Extintor { get; set; }
        public byte? Triangulo { get; set; }
        public byte? RelogioTeto { get; set; }
        public byte? RelogioPainel { get; set; }
        public byte? RadioTocaFitas { get; set; }
        public byte? Cd { get; set; }
        public byte? AutoFalantesDiant { get; set; }
        public byte? AutoFalantesTras { get; set; }
        public byte? Antena { get; set; }
        public byte? AirBag { get; set; }
        public byte? Abs { get; set; }
        public byte? Estepe { get; set; }
        public byte? RadioAmfm { get; set; }
        public byte? QtdAutoFalDiant { get; set; }
        public byte? QtdAutoFalTras { get; set; }
        public byte? EquipEspeciais { get; set; }
        public byte? Calotas { get; set; }
        public byte? ChaveRoda { get; set; }
        public byte? Macaco { get; set; }
        public byte? CintosSeguranca { get; set; }
        public byte? PneuLdd { get; set; }
        public byte? PneuLdt { get; set; }
        public byte? PneuLed { get; set; }
        public byte? PneuLet { get; set; }
        public byte? Ferramentas { get; set; }
        public byte? VidroPortaLdd { get; set; }
        public byte? VidroPortaLdt { get; set; }
        public byte? VidroPortaLed { get; set; }
        public byte? VidroPortaLet { get; set; }
        public byte? ParaBrisa { get; set; }
        public byte? VidroTraseiro { get; set; }
        public byte? QuebraVento { get; set; }
        public byte? Retrovisores { get; set; }
        public byte? PortaTraseira { get; set; }
        public byte? EstofTecido { get; set; }
        public byte? EstofCouro { get; set; }
        public byte? ModuloIe { get; set; }
        public byte? Escapamento { get; set; }
        public byte? PortaDirDiant { get; set; }
        public byte? PortaDirTras { get; set; }
        public byte? PortaEsqDiant { get; set; }
        public byte? PortaEsqTras { get; set; }
        public byte? LateralEsq { get; set; }
        public byte? LateralDir { get; set; }
        public byte? Chaves { get; set; }
        public byte? Fechaduras { get; set; }
        public byte? LimpParaBrisaTras { get; set; }
        public byte? VeicPortas { get; set; }
        public string ObservacoesGerais { get; set; }
        public byte? Quadro { get; set; }
        public byte? Carenagem { get; set; }
        public byte? Farol { get; set; }
        public byte? LanternaTras { get; set; }
        public byte? SetasDiant { get; set; }
        public byte? SetasTras { get; set; }
        public byte? TanqueMoto { get; set; }
        public byte? Banco { get; set; }
        public byte? Bengalas { get; set; }
        public byte? Ignicao { get; set; }
        public byte? Pneus { get; set; }
        public byte? FreioDiant { get; set; }
        public byte? FreioTras { get; set; }
        public byte? ManeteEsq { get; set; }
        public byte? ManeteDir { get; set; }
        public string SvLote { get; set; }
        public DateTime? SvLeilao { get; set; }
        public decimal? DespTransf { get; set; }
        public string ItaucodSeg { get; set; }
        public DateTime? ItaudataPlanilha { get; set; }
        public decimal? AdiantamentoDoc { get; set; }
        public decimal? CustoEfetivoDoc { get; set; }
        public DateTime? DataAdiantamentoDoc { get; set; }
        public DateTime? DataCustoEfetivoDoc { get; set; }
        public bool DiferencaCustoAdiantPaga { get; set; }
        public string NumChequeDiferenca { get; set; }
        public DateTime? DataPagDiferenca { get; set; }
        public bool Protech { get; set; }
        public byte VistoriaRegistrada { get; set; }
        public string AdiantNomeDespachante { get; set; }
        public decimal? AdiantEstadia { get; set; }
        public decimal? AdiantTxLocalizacao { get; set; }
        public decimal? ValorRemocao { get; set; }
        public decimal? ValorGuinchoLocal { get; set; }
        public decimal? ValorEstadia { get; set; }
        public decimal ValorEscob { get; set; }
        public byte? Tacografo { get; set; }
        public byte? EixoCardan { get; set; }
        public byte? TerceiroEixo { get; set; }
        public byte? PainelInstrumentos { get; set; }
        public byte? CaixaTransmissao { get; set; }
        public string DivergenciaVistoria { get; set; }
        public decimal ValorDiligencia { get; set; }
        public decimal ValorVistoriaInLoco { get; set; }
        public decimal ValorCartorio { get; set; }
        public decimal ValorEstadiaNaVenda { get; set; }
        public decimal ValorGuinchoApreensao { get; set; }
        public string EmpresaVistoriaInLoco { get; set; }
        public byte? NivelCombustivel { get; set; }
        public byte? FrenteSom { get; set; }
        public string Renavam { get; set; }
        public byte ChavesQtd { get; set; }
        public byte? CambioTipo { get; set; }
        public byte? Blindado { get; set; }

        public virtual ICollection<MldocumentosVeic> MldocumentosVeic { get; set; }
        public virtual ICollection<MlprocessoTransf> MlprocessoTransf { get; set; }
        public virtual ICollection<MlremocoesVeic> MlremocoesVeic { get; set; }
    }
}
